name: CI



on: workflow_dispatch



jobs:

  build:

    runs-on: windows-latest



    steps:

    - name: Install

      run: pip3 install pyngrok

    - name: Check Installation

      run: ngrok

    - name: Auth

      run: ngrok authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - run: Set-NetFirewallRule -Name "RemoteDesktop-In-TCP-WS" -Enabled True
        
    - run: Get-NetFirewallRule | Where-Object Name -like 'RemoteDesktop*' | Out-String -Stream | Select-String "^Name","Enabled"


    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "PassWD@10" -Force)

    - name: Create Tunnel

      run: ngrok tcp --region ap 3389
